DATA_SEG SEGMENT 
NUM DB 5 
DATA_LIST DW -1,0,2,5,4,5 DUP(?)
MAX DW ? 
MIN DW ? 
DATA_SEG ENDS 
;---------------------------------------------------------------- 
CODE_SEG SEGMENT 
MAIN PROC FAR 
ASSUME CS:CODE_SEG,DS:DATA_SEG
START: PUSH DS ;RETURN DS 
SUB AX,AX 
PUSH AX 
MOV AX,DATA_SEG ;GIVE VALUE TO DS 
MOV DS,AX 
MOV CX,4 ;CODE_SEG START 
LEA BX,DATA_LIST 
MOV AX,[BX] 
MOV MAX,AX 
MOV MIN,AX 
ROUT1: ADD BX,2 
MOV AX,[BX] 
CMP AX,MAX 
JNGE ROUT2 
MOV MAX,AX 
ROUT2: CMP AX,MIN 
JNLE ROUT3 
MOV MIN,AX 
ROUT3: LOOP ROUT1 ;CODE_SEG ENDING
RET 
MAIN ENDP 
CODE_SEG ENDS 
;---------------------------------------------------------------- 
END START