DATA SEGMENT
DATA ENDS
CODE SEGMENT
MAIN PROC FAR
ASSUME CS:CODE,DS:DATA
BEGIN: MOV BX,0 
MOV CX,100 
COMPARE: MOV AX,DATA[BX] ;Get first ODD
ADD BX,2
TEST AX,01H; ODD? 
LOOPNZ COMPARE;No,Next
JNZ STOP ;No ODD Exit
JCXZ STOP ;The Last is ODD ,Exit 
COMPARE1: MOV DX,DATA[BX] ;Get Next ODD 
ADD BX,2 
TEST DX,01H ;ODD?
JNZ NEXT;No,Next
CMP AX,DX ;(AX)<(DX)? 
JLE NEXT 
MOV AX,DX ;if (AX)<(DX) Change (AX) to Min 
NEXT: LOOP COMPARE1 
STOP: RET 
MAIN ENDP
CODE ENDS
END BEGIN